routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('modules.usuarios.form');
// });

Route::get('routes', function() {
    dd(Route::getRoutes());
});

Route::resource('auth', 'UsuarioController', ['except' => ['show']]);
Route::resource('cliente', 'ClienteController', ['except' => ['show']]);
Route::resource('exercicio', 'ExercicioController', ['except' => ['show']]);
Route::resource('musculo', 'MusculoController', ['except' => ['show']]);
Route::resource('serie', 'SerieController', ['except' => ['show']]);
Route::resource('cliente.ficha', 'Academia\FichaController');
Route::resource('cliente.medida', 'Academia\MedidaController', ['except' => ['show']]);


// Route::group(['prefix' => 'api'], function()
// {
// 	Route::group(['prefix' => 'academia'], function()
// 	{
// 		Route::get('', ['uses' => 'AcademiaController@allUsers'] );

// 		Route::get('{id}', ['uses' => 'AcademiaController@getUser'] );

// 		Route::post('', ['uses' => 'AcademiaController@saveUser'] );

// 		Route::put('{id}', ['uses' => 'AcademiaController@updateUser'] );

// 		Route::delete('{id}', ['uses' => 'AcademiaController@deleteUser'] );

// 	});

// });

Route::group(['prefix' => 'api'], function()
{
	Route::group(['prefix' => 'users'], function()
	{
		Route::get('', ['uses' => 'AcademiaController@allClientes'] );

		Route::get('{id}', ['uses' => 'AcademiaController@getCliente'] );

		Route::post('', ['uses' => 'AcademiaController@saveCliente'] );

		Route::put('{id}', ['uses' => 'AcademiaController@updateCliente'] );

		Route::delete('{id}', ['uses' => 'AcademiaController@deleteCliente'] );

	});

});



Auth::routes();

// Route::get('/home', 'HomeController@index');

app/Musculo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Musculo extends Model
{
    protected $table = 'musculos';
    public $timestamps = false;
    protected $primaryKey = 'id_musculo';
    protected $fillable = ['nome_musculo'];

    
}

app/Http/Controllers/MusculoController.php
<?php

namespace App\Http\Controllers;
use App\Musculo;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Input;
use Illuminate\Http\Request;

class MusculoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
         if(Input::has('musculo_search') == false){
            $musculos = DB::table('musculos')->orderBy('nome_musculo')->paginate(5);
        }else{
            $name = $request->musculo_search;
            $musculos = DB::table('musculos')->where('nome_musculo', 'like', '%'.$name.'%')->orderBy('nome_musculo')->paginate(8);
        }

        $data = [
            'data' => $musculos
        ];

        return view('modules.musculos.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('modules.musculos.form')
            ->with('type', 'create')
            ->with('action', route('musculo.store'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $data = $request->musculo;
            $musculo = new Musculo($data);
            $musculo->save();    

            return redirect()
                ->route('musculo.index')
                ->with(['success' => 'musculo cadastrado com sucesso!']);
        } catch (\Exception $e) {
            return redirect()
                ->back()
                ->withInput()
                ->withErrors(['Não foi possível cadastrar o musculo, tente novamente mais tarde!<br>' . $e->getMessage()]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $musculo = Musculo::find($id);

        if (is_null($musculo)) {
            throw new NotFoundHttpException;
        }

        return view('modules.musculos.form')
            ->with('musculo', $musculo)
            ->with('type', 'edit')
            ->with('action', route('musculo.update', $id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $musculo = Musculo::find($id);
            $musculo->fill($request->musculo)->save();

            return redirect()
                ->route('musculo.index')
                ->with(array('success' => 'musculo editado com sucesso!'));
        } catch (\Exception $e) {
            return redirect()
                ->route('musculo.index')
                ->withErrors(['Não foi possível cadastrar o musculo no momento, tente novamente mais tarde!' . $e->getMessage()])
                ->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $musculo = Musculo::find($id);
            if (is_null($musculo)) {
                abort(404);
            }

            $musculo->delete();

            return redirect()
                ->route('musculo.index')
                ->with(array('success' => 'musculo excluido com sucesso!'));
        } catch (\Exception $e) {
            return redirect()
                ->route('musculo.index')
                ->withErrors(['Não foi possível deletar o musculo no momento, tente novamente mais tarde!' . $e->getMessage()])
                ->withInput();
        }
    }
}

resources/views/modules/musculos/form.blade.php
@extends('modules.musculos.module')

@section('module-content')

    <div class="container">
        <form  action="{{$action}}" method="post" enctype="multipart/form-data" class="ui form">
            {!! csrf_field() !!}

            @if ($type == 'edit')
                {{method_field('PUT')}}
            @endif
            
            <div class="ui segment">
                <h4 class="ui header">Criar categoria de musculo:</h4>
                <div class="field">
                    <div class="two fields">
                        <div class="field">
                            <label for="musculo_name">Nome do musculo:</label>
                            <input type="text" id="musculo_name" name="musculo[nome_musculo]" value="{{($type == 'create' ? old('musculo.nome_musculo') : $musculo->nome_musculo)}}" placeholder="First Name"  required>
                        </div>
                    </div>
                    <div class="field">
                        <button type="submit" class="ui green button" name="save">Salvar</button>
                    </div>
                </div>
            </div>
        </form>
    </div>

@endsection

resources/views/modules/musculos/index.blade.php
@extends('modules.musculos.module')

@section('module-content')
    
    <div class="container search">
        <form action="{{route('musculo.index')}}" method="get" enctype="multipart/form-data" class="ui form">
            {!! csrf_field() !!}
            <div class="ui icon input">
              <input type="text" name="musculo_search" placeholder="Search...">
              <i class="circular search link icon"></i>
            </div>
        </form>
    </div>   

    @if (!is_null($data))
        <div class="twelve wide column">
            <table class="ui single line celled table"">
                <thead>
                <tr>
                    <th>Nome</th>
                    <th width="160">Ações</td>
                </tr>
                </thead>
                <tbody>

                    @foreach ($data as $row)
                    <tr>
                        <td>
                            <div class="four wide column">{{$row->nome_musculo}}</div>
                        </td>
                        <td>
                            <form action="{{route('musculo.destroy', $row->id_musculo) }}" method="post" class="ui form" onsubmit="return deleteData();">
                                {!! csrf_field() !!}
                                {!! method_field('DELETE') !!}
                                <a href="{{route('musculo.edit', $row->id_musculo ) }}" class="ui blue icon button" data-tooltip="Editar"><i class="icon edit"></i></a>
                                <button class="ui red icon button btn-remove" data-tooltip="Remover"><i class="icon trash"></i></button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        
        <div>
            @include('layouts.pagination')
        </div>

    @else
        <p>Nenhum registro encontrado.</p>
    @endif

@endsection

resources/views/modules/musculos/module.blade.php
@extends('layouts.dashboard')

@section('content-wizard')

    <div class="action-buttons">
        <a href="{{route('musculo.index')}}" class="ui button teal">Listar musculos</a>
        <a href="{{route('musculo.create')}}" class="ui button teal">Novo musculo</a>
    	@yield('module-content')
    </div>

@endsection