routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('modules.usuarios.form');
// });

Route::get('routes', function() {
    dd(Route::getRoutes());
});

Route::resource('auth', 'UsuarioController', ['except' => ['show']]);
Route::resource('cliente', 'ClienteController', ['except' => ['show']]);
Route::resource('exercicio', 'ExercicioController', ['except' => ['show']]);
Route::resource('musculo', 'MusculoController', ['except' => ['show']]);
Route::resource('serie', 'SerieController', ['except' => ['show']]);
Route::resource('cliente.ficha', 'Academia\FichaController');
Route::resource('cliente.medida', 'Academia\MedidaController', ['except' => ['show']]);


// Route::group(['prefix' => 'api'], function()
// {
// 	Route::group(['prefix' => 'academia'], function()
// 	{
// 		Route::get('', ['uses' => 'AcademiaController@allUsers'] );

// 		Route::get('{id}', ['uses' => 'AcademiaController@getUser'] );

// 		Route::post('', ['uses' => 'AcademiaController@saveUser'] );

// 		Route::put('{id}', ['uses' => 'AcademiaController@updateUser'] );

// 		Route::delete('{id}', ['uses' => 'AcademiaController@deleteUser'] );

// 	});

// });

Route::group(['prefix' => 'api'], function()
{
	Route::group(['prefix' => 'users'], function()
	{
		Route::get('', ['uses' => 'AcademiaController@allClientes'] );

		Route::get('{id}', ['uses' => 'AcademiaController@getCliente'] );

		Route::post('', ['uses' => 'AcademiaController@saveCliente'] );

		Route::put('{id}', ['uses' => 'AcademiaController@updateCliente'] );

		Route::delete('{id}', ['uses' => 'AcademiaController@deleteCliente'] );

	});

});



Auth::routes();

// Route::get('/home', 'HomeController@index');

app/Cliente.php
<?php

namespace App;
use App\FichaExercicio;
use Illuminate\Support\Facades\Input;
use Illuminate\Database\Eloquent\Model;

class Cliente extends Model
{
    protected $table = 'clientes';
    protected $primaryKey = 'id_cliente';
    public $timestamps = false;
    protected $fillable = ['matricula_cliente', 'nome_cliente'];

    public function allClientes()
    {
        $array = [self::all(), FichaExercicio::all()];

        return $array;
    	//return ;
    }

    public function saveCliente()
    {
    	$input = Input::all();
        $cliente = new Cliente();
    	$cliente->fill($input);
    	$cliente->save();
    	return $cliente;
    }

    public function getCliente($id)
    {
        $cliente = self::find($id);

        if(is_null($cliente))
        {
            return false;
        }
        //$ficha = Ficha::find($cliente->id_cliente);
        $fichaExercicio = FichaExercicio::find($cliente->id_cliente);
        $data = [$cliente, $fichaExercicio];
        return $data;
    }

    public function updateCliente($id)
    {
        $Cliente = self::find($id);
        if(is_null($Cliente))
        {
            return false;    
        }
        $input = Input::all();
        $Cliente->fill($input);
        $Cliente->save();
        return $Cliente;
    }

    public function deleteCliente($id)
    {
        $Cliente = self::find($id);
        if(is_null($Cliente))
        {
            return false;
        }
        return $Cliente->delete();
    }
}

app/Http/Controllers/ClienteController.php
<?php

namespace App\Http\Controllers;
use App\Cliente;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Input;
use Illuminate\Http\Request;
use App\Http\Requests\ClienteRequest;

class ClienteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    // protected $messages = [
    //     'cliente.nome_cliente.max:10' => 'O campo nome não pode ter mais de 45 caracteres',
    //     'cliente.matricula_cliente.max:6' => 'A matricula so pode ter no máximo 6 dígitos',
    // ];

    public function index(Request $request)
    {
        if(Input::has('cliente_search') == false){
            $clientes = DB::table('clientes')->orderBy('nome_cliente')->paginate(5);
        }else{
            $name = $request->cliente_search;
            $clientes = DB::table('clientes')->where('nome_cliente', 'like', '%'.$name.'%')->orderBy('nome_cliente')->paginate(8);
        }

        $data = [
            'data' => $clientes
        ];

        return view('modules.clientes.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('modules.clientes.form')
            ->with('type', 'create')
            ->with('action', route('cliente.store'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ClienteRequest $request)
    {
        $matricula = (int)$request->cliente['matricula_cliente'];
        $data = (boolean)DB::table('clientes')->where('matricula_cliente', $matricula)->first();
       
       if($data)
       {
           return redirect()
               ->back()
               ->withInput()
               ->withErrors(['Este cliente já foi cadastrado!<br>']);
       }

       try {
           $data = $request->cliente;
           $data['matricula_cliente'] = (int)$data['matricula_cliente'];
           $cliente = new Cliente($data);
           $cliente->save();    

           return redirect()
               ->route('cliente.index')
               ->with(['success' => 'cliente cadastrado com sucesso!']);
       } catch (\Exception $e) {
           return redirect()
               ->back()
               ->withInput()
               ->withErrors(['Não foi possível cadastrar o cliente, tente novamente mais tarde!<br>' . $e->getMessage()]);
       } 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cliente = Cliente::find($id);

        if (is_null($cliente)) {
            throw new NotFoundHttpException;
        }

        return view('modules.clientes.form')
            ->with('cliente', $cliente)
            ->with('type', 'edit')
            ->with('action', route('cliente.update', $id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $cliente = Cliente::find($id);
            $cliente->fill($request->cliente)->save();

            return redirect()
                ->route('cliente.index')
                ->with(array('success' => 'cliente editado com sucesso!'));
        } catch (\Exception $e) {
            return redirect()
                ->route('cliente.index')
                ->withErrors(['Não foi possível cadastrar o cliente no momento, tente novamente mais tarde!' . $e->getMessage()])
                ->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $cliente = Cliente::find($id);
            if (is_null($cliente)) {
                abort(404);
            }

            $cliente->delete();

            return redirect()
                ->route('cliente.index')
                ->with(array('success' => 'cliente excluido com sucesso!'));
        } catch (\Exception $e) {
            return redirect()
                ->route('cliente.index')
                ->withErrors(['Não foi possível deletar o cliente no momento, tente novamente mais tarde!' . $e->getMessage()])
                ->withInput();
        }
    }
}

resources/views/modules/clientes/form.blade.php
@extends('modules.clientes.module')
@section('module-content')

    <div class="container">
        <form  action="{{$action}}" method="post" enctype="multipart/form-data" class="ui form">
            {!! csrf_field() !!}

            @if ($type == 'edit')
                {{method_field('PUT')}}
            @endif
            
            <div class="ui segment">
                <h4 class="ui header" style="padding-top: 8px">Criar Aluno</h4>
                <div class="ui divider" style="width: 10%"></div>
                <div class="field">
                    <div class="two fields">
                        <div class="field">
                            <label for="cliente_name">Nome:</label>
                            <input type="text" id="cliente_name" name="cliente[nome_cliente]" value="{{($type == 'create' ? old('cliente.nome_cliente') : $cliente->nome_cliente)}}" placeholder="Nome Completo" >
                        </div>
                        <div class="field">
                            <label for="cliente_matricula">Matrícula:</label>
                            <input type="text" id="cliente_matricula" name="cliente[matricula_cliente]" value="{{($type == 'create' ? old('cliente.matricula_cliente') : $cliente->matricula_cliente)}}" placeholder="Matrícula">
                        </div>
                    </div>
                    <div class="two fields">
                        <div class="field">
                            <label for="cliente_name">E-mail:</label>
                            <input type="text" id="cliente_email" name="cliente[email_cliente]" value="{{($type == 'create' ? old('cliente.email_cliente') : $cliente->email_cliente)}}" placeholder="E-mail" >
                        </div>
                        <div class="field">
                            <label for="cliente_matricula">Senha:</label>
                            <input type="password" id="cliente_senha" name="cliente[senha_cliente]" value="{{($type == 'create' ? old('cliente.senha_cliente') : $cliente->senha_cliente)}}" placeholder="Senha">
                        </div>
                    </div>
                    <div class="field">
                        <button type="submit" class="ui green button" name="save">Salvar</button>
                    </div>
                </div>
            </div>
        </form>
    </div>

@endsection

resources/views/modules/clientes/index.blade.php
@extends('modules.clientes.module')

@section('module-content')
    
    <div class="container search">
        <form action="{{route('cliente.index')}}" method="get" enctype="multipart/form-data" class="ui form">
            {!! csrf_field() !!}
            <div class="ui icon input">
              <input type="text" class="search" name="cliente_search" placeholder="Pesquisar cliente...">
              <i class="circular search link icon"></i>
            </div>
        </form>
    </div>
 
    @if (!is_null($data))
        
            <div class="twelve wide column">
                <table class="ui single line celled table"">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nome</th>
                        <th>Matrícula</th>
                        <th width="160">Ações</td>
                    </tr>
                    </thead>
                    <tbody>

                        @foreach ($data as $row)
                        <tr>
                            <td>
                                <div class="four wide column"> {{$row->id_cliente}}</div>
                            </td>
                            <td>
                                <div class="four wide column"> {{$row->nome_cliente}}</div>
                            </td>
                            <td>
                                <div class="four wide column"> {{$row->matricula_cliente}}</div>
                            </td>
                            <td>
                                <form action="{{route('cliente.destroy', $row->id_cliente) }}" method="post" class="ui form" onsubmit="return deleteData();"> 
                                    {!! csrf_field() !!}
                                    {!! method_field('DELETE') !!}
                                    <a href="{{ route('cliente.ficha.index', $row->id_cliente) }}" class="ui teal icon button" data-tooltip="Gerenciar"><i class="icon cogs"></i></a>
                                    <a href="{{route('cliente.edit', $row->id_cliente ) }}" class="ui blue icon button" data-tooltip="Editar"><i class="icon edit"></i></a>
                                    <button class="ui red icon button btn-remove" data-tooltip="Remover"><i class="icon trash"></i></button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>


        <div>
            @include('layouts.pagination')
        </div>

    @else
        <p>Nenhum registro encontrado.</p>
    @endif

    <div class="ui basic modal">
      <div class="ui icon header">
        <i class="archive icon"></i>
        Deseja realmente deletar essas informações?
      </div>
      <div class="actions">
        <div id="cancel" class="ui red basic cancel inverted button">
          <i class="remove icon"></i>
          NÃO
        </div>
        <div id="ok" class="ui green ok inverted button">
          <i class="checkmark icon"></i>
          SIM
        </div>
      </div>
    </div>    

@endsection

resources/views/modules/clientes/module.blade.php
@extends('layouts.dashboard')
@section('content-wizard')

    <div class="container">
        <a href="{{route('cliente.index')}}" class="ui button teal">Listar Clientes</a>
        <a href="{{route('cliente.create')}}" class="ui button teal">Novo Cliente</a>
    	@yield('module-content')
    </div>
    
@endsection