routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('modules.usuarios.form');
// });

Route::get('routes', function() {
    dd(Route::getRoutes());
});

Route::resource('auth', 'UsuarioController', ['except' => ['show']]);
Route::resource('cliente', 'ClienteController', ['except' => ['show']]);
Route::resource('exercicio', 'ExercicioController', ['except' => ['show']]);
Route::resource('musculo', 'MusculoController', ['except' => ['show']]);
Route::resource('serie', 'SerieController', ['except' => ['show']]);
Route::resource('cliente.ficha', 'Academia\FichaController');
Route::resource('cliente.medida', 'Academia\MedidaController', ['except' => ['show']]);


// Route::group(['prefix' => 'api'], function()
// {
// 	Route::group(['prefix' => 'academia'], function()
// 	{
// 		Route::get('', ['uses' => 'AcademiaController@allUsers'] );

// 		Route::get('{id}', ['uses' => 'AcademiaController@getUser'] );

// 		Route::post('', ['uses' => 'AcademiaController@saveUser'] );

// 		Route::put('{id}', ['uses' => 'AcademiaController@updateUser'] );

// 		Route::delete('{id}', ['uses' => 'AcademiaController@deleteUser'] );

// 	});

// });

Route::group(['prefix' => 'api'], function()
{
	Route::group(['prefix' => 'users'], function()
	{
		Route::get('', ['uses' => 'AcademiaController@allClientes'] );

		Route::get('{id}', ['uses' => 'AcademiaController@getCliente'] );

		Route::post('', ['uses' => 'AcademiaController@saveCliente'] );

		Route::put('{id}', ['uses' => 'AcademiaController@updateCliente'] );

		Route::delete('{id}', ['uses' => 'AcademiaController@deleteCliente'] );

	});

});



Auth::routes();

// Route::get('/home', 'HomeController@index');

app/Exercicio.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Exercicio extends Model
{
    protected $table = 'exercicios';
    public $timestamps = false;
    protected $primaryKey = 'id_exercicio';
    protected $fillable = ['nome_exercicio', 'alternativo_exercicio'];

    public function fichas()
	{
	    return $this->belongsToMany('App\Exercicio','ficha_exercico', 'id_forekey_ficha', 'ficha_id');
	}
}

app/Http/Controllers/ExercicioController.php
<?php

namespace App\Http\Controllers;
use App\Exercicio;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Input;
use Illuminate\Http\Request;

class ExercicioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if(Input::has('exercicio_search') == false){
            $exercicios = DB::table('exercicios')->orderBy('nome_exercicio')->paginate(5);
        }else{
            $name = $request->exercicio_search;
            $exercicios = DB::table('exercicios')->where('nome_exercicio', 'like', '%'.$name.'%')->orderBy('nome_exercicio')->paginate(8);
        }

        $data = [
            'data' => $exercicios
        ];

        return view('modules.exercicios.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('modules.exercicios.form')
            ->with('type', 'create')
            ->with('action', route('exercicio.store'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $data = $request->exercicio;
            $exercicio = new Exercicio($data);
            $exercicio->save();    

            return redirect()
                ->route('exercicio.index')
                ->with(['success' => 'exercicio cadastrado com sucesso!']);
        } catch (\Exception $e) {
            return redirect()
                ->back()
                ->withInput()
                ->withErrors(['Não foi possível cadastrar o exercicio, tente novamente mais tarde!<br>' . $e->getMessage()]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $exercicio = Exercicio::find($id);

        if (is_null($exercicio)) {
            throw new NotFoundHttpException;
        }

        return view('modules.exercicios.form')
            ->with('exercicio', $exercicio)
            ->with('type', 'edit')
            ->with('action', route('exercicio.update', $id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $exercicio = Exercicio::find($id);
            $exercicio->fill($request->exercicio)->save();

            return redirect()
                ->route('exercicio.index')
                ->with(array('success' => 'exercicio editado com sucesso!'));
        } catch (\Exception $e) {
            return redirect()
                ->route('exercicio.index')
                ->withErrors(['Não foi possível cadastrar o exercicio no momento, tente novamente mais tarde!' . $e->getMessage()])
                ->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $exercicio = Exercicio::find($id);
            if (is_null($exercicio)) {
                abort(404);
            }

            $exercicio->delete();

            return redirect()
                ->route('exercicio.index')
                ->with(array('success' => 'exercicio excluido com sucesso!'));
        } catch (\Exception $e) {
            return redirect()
                ->route('exercicio.index')
                ->withErrors(['Não foi possível deletar o exercicio no momento, tente novamente mais tarde!' . $e->getMessage()])
                ->withInput();
        }
    }
}

resources/views/modules/exercicios/form.blade.php
@extends('modules.exercicios.module')

@section('module-content')

    <div class="container">
        <form  action="{{$action}}" method="post" enctype="multipart/form-data" class="ui form">
            {!! csrf_field() !!}

            @if ($type == 'edit')
                {{method_field('PUT')}}
            @endif
            
            <div class="ui segment">
                <h4 class="ui header">Criar exercício</h4>
                <div class="field">
                    <div class="two fields">
                        <div class="field">
                            <label for="exercicio_name">Nome do exercício:</label>
                            <input type="text" id="exercicio_name" name="exercicio[nome_exercicio]" value="{{($type == 'create' ? old('exercicio.nome_exercicio') : $exercicio->nome_exercicio)}}" placeholder="First Name"  required>
                        </div>
                    </div>
                    <div class="two fields">
                        <div class="field">
                            <label for="exercicio_matricula">Exercício alternativo:</label>
                            <input type="text" id="exercicio_matricula" name="exercicio[alternativo_exercicio]" value="{{($type == 'create' ? old('exercicio.alternativo_exercicio') : $exercicio->alternativo_exercicio)}}" placeholder="Last Name" required>
                        </div>
                    </div>
                    <div class="field">
                        <button type="submit" class="ui green button" name="save">Salvar</button>
                    </div>
                </div>
            </div>
        </form>
    </div>

@endsection

resources/views/modules/exercicios/index.blade.php
@extends('modules.exercicios.module')

@section('module-content')
    
    <div class="container search">
        <form action="{{route('exercicio.index')}}" method="get" enctype="multipart/form-data" class="ui form">
            {!! csrf_field() !!}
            <div class="ui icon input">
              <input type="text" name="exercicio_search" placeholder="Search...">
              <i class="circular search link icon"></i>
            </div>
        </form>
    </div>   

    @if (!is_null($data))
        <div class="twelve wide column">
            <table class="ui single line celled table"">
                <thead>
                <tr>
                    <th>Nome</th>
                    <th>Alternativo</th>
                    <th width="160">Ações</td>
                </tr>
                </thead>
                <tbody>

                    @foreach ($data as $row)
                    <tr>
                        <td>
                            <div class="four wide column"> {{$row->nome_exercicio}}</div>
                        </td>
                        <td>
                            <div class="four wide column"> {{$row->alternativo_exercicio}}</div>
                        </td>
                        <td>
                            <form action="{{route('exercicio.destroy', $row->id_exercicio) }}" method="post" class="ui form" onsubmit="return deleteData();">
                                {!! csrf_field() !!}
                                {!! method_field('DELETE') !!}
                                <a href="{{route('exercicio.edit', $row->id_exercicio ) }}" class="ui blue icon button" data-tooltip="Editar"><i class="icon edit"></i></a>
                                <button class="ui red icon button btn-remove" data-tooltip="Remover"><i class="icon trash"></i></button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        
        <div>
            @include('layouts.pagination')
        </div>
    
    @else
        <p>Nenhum registro encontrado.</p>
    @endif

@endsection

resources/views/modules/exercicios/module.blade.php
@extends('layouts.dashboard')

@section('content-wizard')

    <div class="container">
        <a href="{{route('exercicio.index')}}" class="ui button teal">Listar Exercícios</a>
        <a href="{{route('exercicio.create')}}" class="ui button teal">Novo Exercício</a>
        @yield('module-content')
    </div>

@endsection