routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('modules.usuarios.form');
// });

Route::get('routes', function() {
    dd(Route::getRoutes());
});

Route::resource('auth', 'UsuarioController', ['except' => ['show']]);
Route::resource('cliente', 'ClienteController', ['except' => ['show']]);
Route::resource('exercicio', 'ExercicioController', ['except' => ['show']]);
Route::resource('musculo', 'MusculoController', ['except' => ['show']]);
Route::resource('serie', 'SerieController', ['except' => ['show']]);
Route::resource('cliente.ficha', 'Academia\FichaController');
Route::resource('cliente.medida', 'Academia\MedidaController', ['except' => ['show']]);


// Route::group(['prefix' => 'api'], function()
// {
// 	Route::group(['prefix' => 'academia'], function()
// 	{
// 		Route::get('', ['uses' => 'AcademiaController@allUsers'] );

// 		Route::get('{id}', ['uses' => 'AcademiaController@getUser'] );

// 		Route::post('', ['uses' => 'AcademiaController@saveUser'] );

// 		Route::put('{id}', ['uses' => 'AcademiaController@updateUser'] );

// 		Route::delete('{id}', ['uses' => 'AcademiaController@deleteUser'] );

// 	});

// });

Route::group(['prefix' => 'api'], function()
{
	Route::group(['prefix' => 'users'], function()
	{
		Route::get('', ['uses' => 'AcademiaController@allClientes'] );

		Route::get('{id}', ['uses' => 'AcademiaController@getCliente'] );

		Route::post('', ['uses' => 'AcademiaController@saveCliente'] );

		Route::put('{id}', ['uses' => 'AcademiaController@updateCliente'] );

		Route::delete('{id}', ['uses' => 'AcademiaController@deleteCliente'] );

	});

});



Auth::routes();

// Route::get('/home', 'HomeController@index');

resources/views/layouts/alerts.blade.php
@if (count($errors) > 0)
    <div class="ui error message">
        <i class="close icon"></i>
        <div class="header">Erro!</div>
        <ul class="list">
            @foreach ($errors->all() as $error)
                <li>{!! $error !!}</li>
            @endforeach
        </ul>
    </div>
@endif

@if (Session::get('success'))
    <div class="ui success message">
        <i class="close icon"></i>
        <div class="header">Sucesso!</div>
        <p>{!! Session::get('success') !!}</p>
    </div>
@endif

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Workout Tracker') }}</title>
    

    <!-- Standard Meta -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <link rel="image_src" type="image/jpeg" href="/images/logo.png" />
    <link rel="icon" href="img/favicon.ico" type="image/x-icon" />
    <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon" />
    <!-- Site Properities -->
    <meta name="generator" content="Visual Studio 2015" />
    <title>Header | Golgi Admin</title>
    <meta name="description" content="Golgi Admin Theme" />
    <meta name="keywords" content="html5, ,semantic,ui, library, framework, javascript,jquery,admin,theme" />
    <link href="{{asset('assets/dist/semantic.min.css')}}" rel="stylesheet" />
    <!-- <link href="{{asset('assets/css/main.min.css')}}" rel="stylesheet" /> -->
    <!-- <link href="{{asset('assets/plugins/pacejs/pace.css')}}" rel="stylesheet" /> -->
    <script src="{{asset('assets/js/jquery-2.1.4.min.js')}}"></script>
    <link rel="stylesheet" href="{{asset('assets/css/style.css')}}">


    <script>
        window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
        ]) !!};
    </script>
</head>
<body>
    <div id="wrapper">
            @yield('content')
    </div>   
</div>

    <!-- Scripts -->
    <!-- <script src="{{asset('assets/plugins/nicescrool/jquery.nicescroll.min.js')}}"></script> -->
    <script src="{{asset('assets/dist/semantic.min.js')}}"></script>
    <!-- <script data-pace-options='{ "ajax": false }' src="{{asset('assets/plugins/pacejs/pace.js')}}"></script> -->
    <!-- <script src="{{asset('assets/js/app.min.js')}}"></script> -->
    <script src="{{asset('assets/js/jquery.mask.min.js')}}"></script>
    <script src="{{asset('assets/js/script.js')}}"></script>
</body>
</html>

resources/views/layouts/dashboard.blade.php
@extends('layouts.app')
@section('content')
@extends('layouts.navbar')

    <div class="ui grid">
        <div class="four wide column">
            @include('layouts.steps')
        </div>
        <div class="twelve wide column" id="dashboard">
            @include('layouts.alerts')
            @yield('content-wizard')
        </div>
    </div>
@endsection

resources/views/layouts/default.blade.php
@extends('layouts.app')
<div class="ui container">
	    
	    <div id="wrapper">
	        <div class="ui container">
	            @yield('content')
	        </div>
	    </div>   
	</div>

resources/views/layouts/internal.blade.php
@extends('layouts.app')
@section('content')
@extends('layouts.navbar')

    <div class="ui grid">
        <div class="four wide column" >
            @include('layouts.internalsteps')
        </div>
        <div class="twelve wide column" id="internalsteps">
            @include('layouts.alerts')
            @yield('content-wizard-internal')
        </div>
    </div>
@endsection

resources/views/layouts/internalsteps.blade.php
<div class="ui secondary vertical pointing menu">
    <div class="ui accordion">
        <div class="title">
            <a class="item" href="{{route('cliente.ficha.index', $cliente->id_cliente)}}">
                Fichas <i class="ordered list icon"></i>
            </a>
            <a class="item" href="{{route('cliente.medida.index', $cliente->id_cliente)}}">
                Medidas <i class="text height icon"></i>
            </a>
        </div>
    </div>
</div>

resources/views/layouts/navbar.blade.php
<div class="ui menu" id="navbar">
    <a class="launch icon item" id="icone-home" href="http://localhost:8000/cliente" style="padding-top:20px;">
        <i class="home icon"></i>
    </a>
    <div class="right menu">
        <div class="ui dropdown item labeled icon"></div>
        <div class="ui dropdown item">
            <img class="ui circular image" id="icone-opcoes" src="{{asset('assets/images/gears.png')}}">
            <div class="menu">
                <a class="item">Sair</a>
            </div>
        </div>
    </div>	    
</div>

resources/views/layouts/pagination.blade.php
<?php $totalPages = ceil($data->total()/$data->perPage()); ?>
@if ($totalPages > 1)
    <div class="ui pagination menu">
        <a class="icon item {{$data->currentPage() != 1 ? null : 'disabled'}}" href="{{$data->currentPage() != 1 ? $data->previousPageUrl() : 'javascript:;'}}">
            <i class="left chevron icon"></i>
        </a>

        @for ($i = $data->currentPage()-3; $i < $data->currentPage()+3; $i++)
            @continue($i <= 0 || $i > $totalPages)
            <a class="item {{$data->currentPage() == $i ? 'active' : null}}" href="{{$data->currentPage() == $i ? 'javascript:;' : $data->url($i)}}">{{$i}}</a>
        @endfor

        <a class="icon item {{$data->currentPage() != $totalPages ? null : 'disabled'}}" href="{{$data->currentPage() != $totalPages ? $data->nextPageUrl() : 'javascript:;'}}">
            <i class="right chevron icon"></i>
        </a>
    </div>
@endif

resources/views/layouts/signin.blade.php
<!DOCTYPE html>
<html>
<head>
    <!-- Standard Meta -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <link rel="image_src" type="image/jpeg" href="/images/logo.png" />
    <link rel="icon" href="img/favicon.ico" type="image/x-icon" />
    <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon" />
    <!-- Site Properities -->
    <meta name="generator" content="Visual Studio" />
    <title>Sign In | Golgi Admin</title>
    <meta name="description" content="Golgi Admin Theme" />
    <meta name="keywords" content="html5, ,semantic,ui, library, framework, javascript,jquery,admin,theme" />
    <link href="dist/semantic.min.css" rel="stylesheet" />
    <link href="css/main.min.css" rel="stylesheet" />
</head>
<body class="signin">

    <div class="ui container">
        <div class="ui equal width center aligned padded grid stackable">
            <div class="row">
                <div class="five wide column">
                    <div class="ui segments">
                        <div class="ui segment inverted nightli">
                            <h3 class="ui header">
                                Sign in with your Golgi Account
                            </h3>
                        </div>
                        <div class="ui segment">
                            <div class="description">
                                Enter your email address and password.
                            </div>
                            <div class="ui divider"></div>
                            <div class="ui input fluid">
                                <input type="text" placeholder="Your Email...">
                            </div>
                            <div class="ui divider hidden"></div>
                            <div class="ui input fluid">
                                <input type="text" placeholder="Your Password...">
                            </div>
                            <div class="ui divider hidden"></div>

                            <div class="g-recaptcha" data-sitekey="6LeR3xkTAAAAAKFv-HT60HvhrqHGMfQYHup1JFI2"></div>
                            <div class="ui divider hidden"></div>
                            <button class="ui primary fluid button">
                                <i class="key icon"></i>
                                Sign In
                            </button>
                            <div class="ui divider hidden"></div>
                            <a href="forgotpassword.html" class="ui">I Forgot Password?</a>
                            <div class="ui hidden divider"></div>
                            Do not have an account? <a href="signup.html" class="ui">Sign Up</a>
                        </div>
                    </div>
                </div>

            </div>
            
        </div>
    </div>
    

    
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
    <script type="text/javascript">
        var onloadCallback = function () {
            alert("grecaptcha is ready!");
        };
    </script>
</body>
</html>

resources/views/layouts/steps.blade.php
<div class="ui secondary vertical pointing menu" id="steps">
    <div class="ui accordion">
        <div class="title">
            <a class="item" href="{{route('cliente.index')}}">
                Cliente <i class="user icon"></i>
            </a>
            <a class="item" href="{{route('exercicio.index')}}">
                Exercicio <i class="child icon"></i>
            </a>
        </div> 
    </div>
</div>